services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Emilia-tan
      MYSQL_DATABASE: emilia
      MYSQL_PASSWORD: Emilia-tan

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Emilia-tan

volumes:
  db_data:
